image_repo: public.ecr.aws/m5q3e4b2/prow
images:
  docs: prow-docs-0.0.9

  unit-test: prow-unit-0.0.5
  integration-test: prow-integration-0.0.17
  soak-test: prow-soak-0.0.6

  auto-generate-controllers: prow-auto-generate-controllers-0.0.11
  auto-update-controllers: prow-auto-update-controllers-0.0.4
  controller-release-tag: prow-controller-release-tag-0.0.3
  deploy: prow-deploy-0.0.14

  olm-test: prow-olm-test-a21334a
  olm-bundle-pr: prow-olm-bundle-pr-a21334a
